### ISSUE TITLE
Adding mapping option to allow silent ignoring non-existing setters

### ISSUE THREAD

**Issue by dmitrydrugi** [awslabs/rds-data-api-client-library-java#10]
Hi Team,

Could you please add mapping option to allow **silent ignoring** non-existing setters?

It throws the error if there is a field in data set without corresponded field (setter) in Java DTO object.

Thank you.

**Comment by sp0l** [comment]
A new flag `ignoreMissingSetters` (false by default) has been [added](https://github.com/awslabs/rds-data-api-client-library-java/commit/02da7b493644ba9d79f6e76ab5abab249936a79e) to the MappingOptions.
