### ISSUE TITLE
Use ColumnMetadata.label instead of ColumnMetadata.name when extracting field names

### ISSUE THREAD

**Issue by pmalon** [awslabs/rds-data-api-client-library-java#2]
Currently you use `ColumnMetadata.getName()` when extracting field names which leads to problems when one uses snake_case for naming columns - problem could be easily resolved by modifying SQL query to aliases for columns (i.e.: select message_uuid as messageUuid) but `ExecutionResult.extractFieldNames` would have to be modified to use `label` instead of `name`

**Comment by sp0l** [comment]
The ability to use label instead of name is added. Now when you construct an `RdsDataClient`, you can provide a `MappingOptions` instance specifying that you want to use label for mapping:
```
        client = RdsDataClient.builder()
                ...
                .mappingOptions(MappingOptions.DEFAULT.withUseLabelForMapping(true))
                .build();
```
(The default value is `false` for backward compatibility purposes)
