### ISSUE TITLE
AWS Java SDK 2.x upgrade

### ISSUE THREAD

**Issue by colm-madigan** [awslabs/rds-data-api-client-library-java#7]
Currently this project has a dependency on AWS Java SDK 1.x. 
Are there any plans for an upgrade soon to version 2.x?  
What is the best approach to tackle this if I create a PR to do this?

**Comment by GuptaSunny** [comment]
Is there any plan to provide AWS Java SDK 2.x support soon?

**Comment by duncpro** [comment]
Here's a Java 8 wrapper for the RDS Data API based on SDK v2. https://github.com/duncpro/jackal

**Comment by sp0l** [comment]
Data API client library now supports AWS SDK 2.0.
