### ISSUE TITLE
Replacing getDeclaredMethods/getDeclaredField methods to getMethods/getField to support inheritance for DTO objects

### ISSUE THREAD

**Issue by dmitrydrugi** [awslabs/rds-data-api-client-library-java#9]
Hi Team,

Could you please replace getDeclaredMethods/getDeclaredField methods to getMethods/getField to support inheritance for DTO objects:
 - https://github.com/awslabs/rds-data-api-client-library-java/search?q=getDeclaredMethods
 - https://github.com/awslabs/rds-data-api-client-library-java/search?q=getDeclaredField

Example:

```
public class DomainObject {
    private Long id;
    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

public class BusinessObject extends DomainObject {
    private String description;

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}

    ...
    public Response findAll(Request request) {
        client.forSql(SELECT_ALL_SQL)
                .execute()
                .mapToList(BusinessObject.class);
    ...

```

Right now we get the error stating about non-exiting setters for id and name field.

Could you please add a mapping option or change the existing implementation to use getMethods/getField?

Thank you.

**Comment by sp0l** [comment]
The implementation is [changed](https://github.com/awslabs/rds-data-api-client-library-java/commit/ca2c4e192ceae4e446fdf99fd255c186a2b907a3) to getField/getMethod (with the fallback to  getDeclaredField/getDeclaredMethod to access private fields/methods).
